### ISSUE TITLE
ADS8686 write_reg_bridge default clk_div

### ISSUE THREAD

**Issue by lucask07** [Ajstros/pyripherals#15]
The default setting for the ADS8686 register bridge writing results in a sampling rate of 200 kHz. We should consider changing the default to 1 MSPS by setting clk_div=200. 

`ads.write_reg_bridge()` is a clk_div of 1000 which results in a 200 ksps sampling rate below capabilities 

Preferred behavior of 1 MSPS requires:
`ads.write_reg_bridge(clk_div=200)`

https://github.com/Ajstros/pyripherals/blob/main/python/src/pyripherals/peripherals/ADS8686.py#L106

**Comment by Ajstros** [comment]
To preserve older code, we will not change the default. New code should use `ADS8686.write_reg_bridge(clk_div=200)` to get the correct sample rate. For the related issue with the DAC80508, new code should use `DAC80508.set_spi_sclk_divide(0x2)` rather than the `0x8` value from before.
