### ISSUE TITLE
what is pypanel?

### ISSUE THREAD

**Issue by untzag** [Ajstros/pyripherals#23]
Your docs state:

> The register index holds the name, address, lower bit index, upper bit index, and bit width of registers so they can be read in by pypanel and stored in a Register object.

What is pypanel?

**Comment by Ajstros** [comment]
Thank you for pointing this out. This was a typo from a previous version of the package name. It has been updated to *pyripherals* in commit ddaf80a76d39e01f681bc34bcdf1828dea73f994.
