### ISSUE TITLE
why both registers spreadsheet and interface class

### ISSUE THREAD

**Issue by untzag** [Ajstros/pyripherals#24]
I appreciate your New Peripheral Guide, but it raises some design questions for me. Why is pyripherals designed with a unique spreadsheet and unique class for each chip? If we need a unique class, I would have assumed that the class itself would be the best place to store register information.

You mention somewhere that the spreadsheet might be customized by end-users for their specific setup. How would that work exactly?

Perhaps the answer to this question could be included in some high level documentation.

**Comment by Ajstros** [comment]
The spreadsheet is useful in addition to unique chip classes for flexibility. As stated in the JOSS submission paper,

>The spreadsheet organization of data fields allows for user-friendly editing and sharing of data field information without the need to change user code.

If a user decides to change the name or address or bit indices of a bit field, they need only edit the spreadsheet, not constants or variables in their code. This is especially useful for people working on chips that are not yet included in pyripherals. They can instantiate a higher level class like I2CController or SPIController to get the general functionality of a chip, then use a custom spreadsheet page to include the registers for their unique chip.
